### ISSUE TITLE
Use of "c4.9xlarge"?

### ISSUE THREAD

**Issue by sarahbaka** [HPCE/hpce-2018-cw4#40]
Is this meant to say c5.9xlarge instead of c4.9xlarge? The latter doesn't exist on AWS.

<img width="812" alt="screen shot 2019-02-06 at 17 25 08" src="https://user-images.githubusercontent.com/19685423/52360545-3fe2b980-2a34-11e9-80c8-69cb17d220ef.png">

**Comment by jjd06** [comment]
Yes, that's a typo -- thanks.
