### ISSUE TITLE
Automated Tests

### ISSUE THREAD

**Issue by mantzouj** [HPCE/hpce-2018-cw4#42]
Have the automated tests started yet? Just want to make sure there isn't something wrong with my repository/etc since for the other assignments, by Wednesday they have run once or twice.

**Comment by jjd06** [comment]
I was intending for these to start earlier today, but I've been having AWS trouble (seems to now be resolved). There's a run going as I type this.

**Comment by swarth100** [comment]
Is it possible to have a final test run this evening?

**Comment by jjd06** [comment]
Please see #45.
