### ISSUE TITLE
Failing Test 33

### ISSUE THREAD

**Issue by moh1ka** [HPCE/hpce-2018-cw4#44]
When checking my implementation of clustered against simple using diff I do not find any differences, yet I am failing test 33 :  

I am using the following procedure to check my implementation:
```
bin/generate_sparse_layer 8 12 > w/layer_8_12.bin
cat /dev/urandom | head -c 2048 > w/random2048.bin
cat w/random2048.bin | bin/run_network w/layer_8_12.bin > w/ref2048.bin
./scripts/create_n512.sh

cat w/random2048.bin | \
   bin/run_network w/n512_00.bin:simple \
   > w/random2048_simple.out

cat w/random2048.bin | \
   bin/run_network w/n512_00.bin:clustered \
   > w/random2048_clustered.out

diff w/random2048_simple.out w/random2048_clustered.out
```

Is there something I am missing?

**Comment by jjd06** [comment]
Try running these with a timeout. I'm killing executions after 30 seconds out of necessity during testing. If you do the same, I suspect you'll find that your executions don't complete in time.
